project: 
  type: website
  output-dir: outputs

website:
  title: "Affordable Housing Tax Credit"
  navbar:
    left:
      - href: mock_website.qmd
        text: Home
      - index.html
      - definitions.qmd
    